# Generated by Django 4.1.5 on 2023-02-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='album',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='songs',
            name='artist',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='songs',
            name='link',
            field=models.FileField(max_length=600, upload_to='music/'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='name',
            field=models.CharField(max_length=600),
        ),
    ]
