# Generated by Django 4.1.5 on 2023-02-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0002_alter_songs_album_alter_songs_artist_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='songs',
            new_name='song',
        ),
    ]
