# Generated by Django 4.1.5 on 2023-02-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0003_rename_songs_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('album', models.CharField(max_length=500)),
                ('artist', models.CharField(max_length=500)),
                ('length', models.DurationField()),
                ('link', models.FileField(max_length=600, upload_to='music/')),
            ],
        ),
        migrations.DeleteModel(
            name='song',
        ),
    ]
