# Generated by Django 4.1.5 on 2023-02-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='favorite_bool',
            field=models.BooleanField(default=False),
        ),
    ]
